CREATE TABLE STUDENT(
STUDENT_ID INTEGER,
SURNAME CHAR (25),
NAME CHAR (10),
STIPEND INTEGER ,
KURS INTEGER,
CITY CHAR (15),
BIRTHDAY DATE,
UNIV_ID INTEGER
);

CREATE TABLE STUDENT(
STUDENT_ID INTEGER NOT NULL UNIQUE,
SURNAME VARCHAR(25) NOT NULL,
NAME VARCHAR(10) NOT NULL,
STIPEND INTEGER ,
KURS INTEGER,
CITY VARCHAR(15),
BIRTHDAY DATE,
UNIV_ID INTEGER,
UNIQUE (SURNAME, BIRTHDAY)
);

Bal integer CHECK ( Bal > 60),


CREATE TABLE STUDENT1(
STUDENT_ID INTEGER NOT NULL,
SURNAME CHAR (25),
NAME CHAR (10),
STIPEND INTEGER CHECK (STIPEND >= 5000),
KURS INTEGER,
CITY CHAR (15),
BIRTHDAY DATE,
UNIV_ID INTEGER CHECK (UNIV_ID = 0),
UNIQUE (SURNAME, KURS)
);

CREATE TABLE STUDENT1(             // конечная версия
STUDENT_ID INTEGER NOT NULL,
SURNAME CHAR (25),
NAME CHAR (10),
STIPEND INTEGER CHECK (STIPEND >= 5000),
KURS INTEGER,
CITY CHAR (15),
BIRTHDAY DATE,
UNIV_ID INTEGER DEFAULT 0,
UNIQUE (SURNAME, KURS)
);